### ISSUE TITLE
User Avatars

### ISSUE THREAD

**Issue by disbelief** [philpee2/AirbnPool#21]
Everyone dump your avatars into comments here!

/cc @philpee2 @SherryHuangUS @warrenshen @disbelief @poyanp

**Comment by disbelief** [comment]
![worli](https://cloud.githubusercontent.com/assets/295574/16468692/035d1ada-3e02-11e6-99bb-683b5ce64935.jpg)

**Comment by warrenshen** [comment]
![image](https://cloud.githubusercontent.com/assets/8787796/16472729/39547fc0-3e1b-11e6-96bd-7e0af75f4f15.png)

**Comment by philpee2** [comment]
![image](https://cloud.githubusercontent.com/assets/2244653/16473858/408afb56-3e26-11e6-96fe-06f66311920b.png)

**Comment by philpee2** [comment]
@SherryHuangUS @poyanp Can you add images here
