### ISSUE TITLE
Improve the voted icon

### ISSUE THREAD

**Issue by philpee2** [philpee2/AirbnPool#33]
Currently looks like this 
![image](https://cloud.githubusercontent.com/assets/2244653/16475225/beb09bca-3e31-11e6-89f9-8f50980b613a.png)

**Comment by poyanp** [comment]
![checkmark 2x](https://cloud.githubusercontent.com/assets/10603198/16498718/e3c20f7c-3eb1-11e6-9649-41f777fe1db6.png)
@philpee2

**Comment by poyanp** [comment]
There an image of a checkmark attached there.

**Comment by warrenshen** [comment]
I got this one!

**Comment by philpee2** [comment]
Why was this closed? @poyanp ?

**Comment by poyanp** [comment]
Clicked the wrong thing. Woops!

**Comment by warrenshen** [comment]
Finished.
