### ISSUE TITLE
Move voteCount attribute to ListingGroups

### ISSUE THREAD

**Issue by disbelief** [philpee2/AirbnPool#42]
It's on Listing right now but listings can be in multiple groups. Will work for this demo since there's only one group.

**Comment by philpee2** [comment]
I can take this one. It's currently messed up the value of each vote (ie it has more value if there are more beds)

**Comment by disbelief** [comment]
`votes.create` is going to need to accept a third argument for the number of votes?

**Comment by philpee2** [comment]
Ideally it would figure it out based on the user who's voting. 
I'm thinking of going back to the slower way of getting the votes per listing. We don't need to care about perf right now, and it's probably simpler/less error-prone to denormalize the data. That way we don't have to manually maintain consistency between collections.
